jwt.secret="MyVeryStrongSecretKeyForJwtAuthentication2026Secure123"
jwt.expiration-ms=3600000

spring.application.name=fincore-banking-system 
spring.datasource.url=jdbc:mysql://localhost:3306/fincorebankingapiapplication
spring.datasource.username=root
spring.datasource.password=Sethu@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bluelightmmm@gmail.com
spring.mail.password=vxbdtoizquffovue
spring.mail.properties.mail.smtp.auth=true;
spring.mail.properties.mail.smtp.starttls.enable=true